### PR TITLE
Added setup form and settings class

### PR DESCRIPTION
**Pull request by RickDB**
- Added setup form which can be opened via context menu, if it detects the default configuration it will launch on startup to allow for user setup.
- Migrated settings to separate class and allowed for configuration manager changes.

### CODE REVIEW

**Comment by hanselb** [comment]
This is amazing stuff @RickDB :+1: I'll merge and create a new release with it.

**Comment by hanselb** [comment]
Hey @RickDB
Just finished going through your code and it's very good. I like the way you decided to handle the re-init and the settings. I am going to go through Resharper's recommendations, so there might be a little refactoring that comes out of that but no logic change.

I am also going to play with the SetupForm design, add to the input validation, figure out a way to get the monitor index automatically, add a start/stop button to the SetupForm.

Thanks for all your contributions so far :smile:

**Comment by hanselb** [comment]
@RickDB I just pushed the changes from using Resharper. Please use that as your development base to minimize merging issues for pull requests in the future.

**Comment by RickDB** [comment]
Thanks for the merge, will re-base on your latest one :)

**Comment by RickDB** [comment]
Btw for default settings would keep it at 0.0.0.0 for the IP / Host as otherwise it will not connect on first start or launch first time setup window.

// Update

App.config from repo looks to do that already however installer is using the old one it seems, maybe needs a small tweak as to not overwrite existing configurations.

**Pull request merged**
